version: "3.3"
services:
  
  database:
    image: mariadb:10.6.5
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    # 실전에서는 비밀번호 등을 이곳에 입력하지 말 것!
    # 서버의 환경변수 등을 활용하세요.
    environment:
      - MYSQL_ROOT_PASSWORD=ssafy
      - MYSQL_DATABASE=neardb
      - TZ=Asia/Seoul
    volumes:
      - ./dev/db_data:/var/lib/mysql
    ports:
      - 3306:3306
  
  backend:
    depends_on:
      - database
    build: ./server
    volumes:
      - ./dev/be:/usr/src/app
    ports:
      - 8185:8185

  frontend:
    build: ./client
    volumes:
      - /app/node_modules
      - ./dev/fe:/home/node/app
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443
    expose:
      - '80'
      - '443'
    command: '/bin/sh -c''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    container_name: certbot_service
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    entrypoint: "/bin/sh - c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
