version: "3.3"
services:
  
  database:
    image: mariadb:10.6.5
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    # 실전에서는 비밀번호 등을 이곳에 입력하지 말 것!
    # 서버의 환경변수 등을 활용하세요.
    environment:
      - MYSQL_ROOT_PASSWORD=ssafy
      - MYSQL_DATABASE=neardb
      - TZ=Asia/Seoul
    volumes:
      - ./dev/db_data:/var/lib/mysql
    ports:
      - 3306:3306
  
  backend:
    depends_on:
      - database
    build: ./server
    volumes:
      - ./dev/be:/usr/src/app
    ports:
      - 8185:8185

  frontend:
    build: ./client
    volumes:
      - /app/node_modules
      - ./dev/fe:/home/node/app
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/certbot/www:/var/www/certbot
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443
    
    
